name: CarScore CI

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Installer pnpm
        run: npm install -g pnpm

      - name: Tester le backend
        run: |
          cd Back
          pnpm install --no-frozen-lockfile
          pnpm test

      - name: Tester le frontend
        run: |
          cd Front
          pnpm install --no-frozen-lockfile
          pnpm test

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Déployer sur Render
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}